name: Publish NuGet Package

on:
  push:
    branches:
      - main  # Укажите ветку, в которой изменения будут триггерить процесс

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Проверка репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установить .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Укажите нужную версию .NET SDK

    # Сборка проекта
    - name: Build project
      run: dotnet build --configuration Release

    # Запуск тестов
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # Публикация NuGet-пакета
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet pack --configuration Release
        dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY     
