name: Build and Publish .NET Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./artifacts src/Blazor.FloatingUI

      - name: Publish package to GitHub Packages
        run: dotnet nuget push ./artifacts/*.nupkg --source "github" --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

